# Generated by Django 4.2.10 on 2024-03-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.AddField(
            model_name='product',
            name='image_large',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='product_images/large/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_medium',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='product_images/medium/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_small',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='product_images/small/'),
        ),
    ]
